language: node_js

node_js:
  - "stable"

cache:
  directories:
  - node_modules

script:
  - CI=true npm test

jobs:
  include:
    - stage: deploy datasette-vega-latest.datasette.io
      on: master
      script:
        - npm install -g now
        - REACT_APP_STAGE=dev npm run build
        - echo '{"name":"datasette-vega-latest","alias":"datasette-vega-latest.datasette.io"}' > build/now.json
        - cd build && now --name=datasette-vega-latest --token=$NOW_TOKEN
        - now alias --token=$NOW_TOKEN
    - stage: release tagged version
      if: tag IS present
      language: python
      python: 3.6
      script:
        - pip install -U pip wheel
      deploy:
        - provider: pypi
          user: simonw
          distributions: bdist_wheel
          password:
            secure: Sl2jbgIhnr2IMHh3Hqg4yO0UsAOS/GYyJf3KdqfCHRHVTiHZaIKqMzcy/ErNzj11vqZcKHDdKEXWtqRLhKL6ZUlHxDeFa3wrfIe8QXwCnn1gmQddvl06ydr2WXjUKyL6f+q6pfON5O6R40NUqXxDr78YIE+uOu4FFJLODfSNRZxf6BP0qLU2wiDf86wxJf95kG3DPGNx2JRGQJqI2jSY30BL0QUCBpwHfF1wpzEp7+nX1vCnEEz2LsP8xGPDzFwNuj8px5HDjK6rRw9M8LP6CKsa65IK2pFwrOmLF0DnperwmgKBzF+atke/NQUlfHAaLjVKvA2w4Ff2xuH8v5ZGGg/gTi283CfFNhWHs2TGAZevAmsrRFKDhG6lTIUhCMSqcleL0moHZXoW0M5Xuwe3qQgJ8jw7OFJTJ3iGRzQnThp70F4XiHLeu+u0gvJOaNmG/xA/fVf6fFZbvCciIaqMrrdC0s/RLmsSOAMz8I767Pnby55Srlk8aYjlKma8lX37UlwYiF+xKgmHuXNtX0x1eQtFedFSgGLpXSsI6MyFcMbghmaTIPS6if8UfX1notbk6lb++nZiZ3ci4/Htl0t4zGBc1WAuBIlfYeS67JuiDXORP/XJRf+k6I4qsZJfInX5R1Nl2JiCNvc51o5fERu3RQpt8rob/46mOZx8UMcH9JY=
          on:
            branch: master
            tags: true
            repo: simonw/datasette-vega
