language: node_js

node_js:
  - "stable"

cache:
  directories:
  - node_modules

script:
  - CI=true npm test

jobs:
  include:
    - stage: deploy datasette-vega-latest.datasette.io
      on: master
      script:
        - npm install -g now
        - REACT_APP_STAGE=dev npm run build
        - echo '{"name":"datasette-vega-latest","alias":"datasette-vega-latest.datasette.io"}' > build/now.json
        - cd build && now --name=datasette-vega-latest --token=$NOW_TOKEN
        - now alias --token=$NOW_TOKEN
